package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Affectation generated by hbm2java
 */
@Entity
@Table(name = "affectation", catalog = "gestion_carburant_db")
public class Affectation implements java.io.Serializable {

	private AffectationId id;
	private Cadre cadre;
	private Voiture voiture;
	private Date dateRetour;

	public Affectation() {
		cadre = new Cadre();
		voiture = new Voiture();
	}

	public Affectation(AffectationId id, Cadre cadre, Voiture voiture, Date dateRetour) {
		this.id = id;
		this.cadre = cadre;
		this.voiture = voiture;
		this.dateRetour = dateRetour;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "matriculeCadre", column = @Column(name = "matricule_cadre", nullable = false, length = 8)),
			@AttributeOverride(name = "matriculeVoiture", column = @Column(name = "matricule_voiture", nullable = false, length = 10)),
			@AttributeOverride(name = "dateAffectation", column = @Column(name = "date_affectation", nullable = false, length = 10)) })
	public AffectationId getId() {
		return this.id;
	}

	public void setId(AffectationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matricule_cadre", nullable = false, insertable = false, updatable = false)
	public Cadre getCadre() {
		return this.cadre;
	}

	public void setCadre(Cadre cadre) {
		this.cadre = cadre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "matricule_voiture", nullable = false, insertable = false, updatable = false)
	public Voiture getVoiture() {
		return this.voiture;
	}

	public void setVoiture(Voiture voiture) {
		this.voiture = voiture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_retour", nullable = true, length = 10)
	public Date getDateRetour() {
		return this.dateRetour;
	}

	public void setDateRetour(Date dateRetour) {
		this.dateRetour = dateRetour;
	}

}
