package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BonCadreId generated by hbm2java
 */
@Embeddable
public class BonCadreId implements java.io.Serializable {

	private String matriculeCadre;
	private int idBonCarburant;
	private Date dateAffectation;

	public BonCadreId() {
	}

	public BonCadreId(String matriculeCadre, int idBonCarburant, Date dateAffectation) {
		this.matriculeCadre = matriculeCadre;
		this.idBonCarburant = idBonCarburant;
		this.dateAffectation = dateAffectation;
	}

	@Column(name = "matricule_cadre", nullable = false, length = 8)
	public String getMatriculeCadre() {
		return this.matriculeCadre;
	}

	public void setMatriculeCadre(String matriculeCadre) {
		this.matriculeCadre = matriculeCadre;
	}

	@Column(name = "id_bon_carburant", nullable = false)
	public int getIdBonCarburant() {
		return this.idBonCarburant;
	}

	public void setIdBonCarburant(int idBonCarburant) {
		this.idBonCarburant = idBonCarburant;
	}

	@Column(name = "date_affectation", nullable = false, length = 10)
	public Date getDateAffectation() {
		return this.dateAffectation;
	}

	public void setDateAffectation(Date dateAffectation) {
		this.dateAffectation = dateAffectation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BonCadreId))
			return false;
		BonCadreId castOther = (BonCadreId) other;

		return ((this.getMatriculeCadre() == castOther.getMatriculeCadre())
				|| (this.getMatriculeCadre() != null && castOther.getMatriculeCadre() != null
						&& this.getMatriculeCadre().equals(castOther.getMatriculeCadre())))
				&& (this.getIdBonCarburant() == castOther.getIdBonCarburant())
				&& ((this.getDateAffectation() == castOther.getDateAffectation())
						|| (this.getDateAffectation() != null && castOther.getDateAffectation() != null
								&& this.getDateAffectation().equals(castOther.getDateAffectation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMatriculeCadre() == null ? 0 : this.getMatriculeCadre().hashCode());
		result = 37 * result + this.getIdBonCarburant();
		result = 37 * result + (getDateAffectation() == null ? 0 : this.getDateAffectation().hashCode());
		return result;
	}

}
