package com.pfe.gestioncarburant.entities;
// Generated Jun 3, 2018 4:40:02 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BonMissionId generated by hbm2java
 */
@Embeddable
public class BonMissionId implements java.io.Serializable {

	private int idMission;
	private int idBonCarburant;
	private Date dateAffectation;

	public BonMissionId() {
	}

	public BonMissionId(int idMission, int idBonCarburant, Date dateAffectation) {
		this.idMission = idMission;
		this.idBonCarburant = idBonCarburant;
		this.dateAffectation = dateAffectation;
	}

	@Column(name = "id_mission", nullable = false)
	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

	@Column(name = "id_bon_carburant", nullable = false)
	public int getIdBonCarburant() {
		return this.idBonCarburant;
	}

	public void setIdBonCarburant(int idBonCarburant) {
		this.idBonCarburant = idBonCarburant;
	}

	@Column(name = "date_affectation", nullable = false, length = 10)
	public Date getDateAffectation() {
		return this.dateAffectation;
	}

	public void setDateAffectation(Date dateAffectation) {
		this.dateAffectation = dateAffectation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BonMissionId))
			return false;
		BonMissionId castOther = (BonMissionId) other;

		return (this.getIdMission() == castOther.getIdMission())
				&& (this.getIdBonCarburant() == castOther.getIdBonCarburant())
				&& ((this.getDateAffectation() == castOther.getDateAffectation())
						|| (this.getDateAffectation() != null && castOther.getDateAffectation() != null
								&& this.getDateAffectation().equals(castOther.getDateAffectation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMission();
		result = 37 * result + this.getIdBonCarburant();
		result = 37 * result + (getDateAffectation() == null ? 0 : this.getDateAffectation().hashCode());
		return result;
	}

}
