package com.pfe.gestioncarburant.entities;
// Generated Jun 3, 2018 4:40:02 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BonMission generated by hbm2java
 */
@Entity
@Table(name = "bon_mission", catalog = "gestion_carburant_db")
public class BonMission implements java.io.Serializable {

	private BonMissionId id;
	private BonCarburant bonCarburant;
	private Mission mission;
	private int qte;

	public BonMission() {
	}

	public BonMission(BonMissionId id, BonCarburant bonCarburant, Mission mission, int qte) {
		this.id = id;
		this.bonCarburant = bonCarburant;
		this.mission = mission;
		this.qte = qte;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMission", column = @Column(name = "id_mission", nullable = false)),
			@AttributeOverride(name = "idBonCarburant", column = @Column(name = "id_bon_carburant", nullable = false)),
			@AttributeOverride(name = "dateAffectation", column = @Column(name = "date_affectation", nullable = false, length = 10)) })
	public BonMissionId getId() {
		return this.id;
	}

	public void setId(BonMissionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_bon_carburant", nullable = false, insertable = false, updatable = false)
	public BonCarburant getBonCarburant() {
		return this.bonCarburant;
	}

	public void setBonCarburant(BonCarburant bonCarburant) {
		this.bonCarburant = bonCarburant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mission", nullable = false, insertable = false, updatable = false)
	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	@Column(name = "qte", nullable = false)
	public int getQte() {
		return this.qte;
	}

	public void setQte(int qte) {
		this.qte = qte;
	}

}
