package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BonMissionId generated by hbm2java
 */
@Embeddable
public class BonMissionId implements java.io.Serializable {

	private int idMission;
	private int idBonCarburant;

	public BonMissionId() {
	}

	public BonMissionId(int idMission, int idBonCarburant) {
		this.idMission = idMission;
		this.idBonCarburant = idBonCarburant;
	}

	@Column(name = "id_mission", nullable = false)
	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

	@Column(name = "id_bon_carburant", nullable = false)
	public int getIdBonCarburant() {
		return this.idBonCarburant;
	}

	public void setIdBonCarburant(int idBonCarburant) {
		this.idBonCarburant = idBonCarburant;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BonMissionId))
			return false;
		BonMissionId castOther = (BonMissionId) other;

		return (this.getIdMission() == castOther.getIdMission())
				&& (this.getIdBonCarburant() == castOther.getIdBonCarburant());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMission();
		result = 37 * result + this.getIdBonCarburant();
		return result;
	}

}
