package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cadre generated by hbm2java
 */
@Entity
@Table(name = "cadre", catalog = "gestion_carburant_db")
public class Cadre implements java.io.Serializable {

	private String matricule;
	private Categorie categorie;
	private Departement departement;
	private Employee employee;
	private Set<BonCadre> bonCadres = new HashSet<BonCadre>(0);
	private Set<Mission> missions = new HashSet<Mission>(0);
	private Set<Affectation> affectations = new HashSet<Affectation>(0);

	public Cadre() {
		employee = new Employee();
		departement = new Departement();
		categorie = new Categorie();
	}

	public Cadre(Categorie categorie, Departement departement, Employee employee) {
		this.categorie = categorie;
		this.departement = departement;
		this.employee = employee;
	}

	public Cadre(Categorie categorie, Departement departement, Employee employee, Set<BonCadre> bonCadres,
			Set<Mission> missions, Set<Affectation> affectations) {
		this.categorie = categorie;
		this.departement = departement;
		this.employee = employee;
		this.bonCadres = bonCadres;
		this.missions = missions;
		this.affectations = affectations;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "employee"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "matricule", unique = true, nullable = false, length = 8)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_categorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_departement", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cadre")
	public Set<BonCadre> getBonCadres() {
		return this.bonCadres;
	}

	public void setBonCadres(Set<BonCadre> bonCadres) {
		this.bonCadres = bonCadres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cadre")
	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cadre")
	public Set<Affectation> getAffectations() {
		return this.affectations;
	}

	public void setAffectations(Set<Affectation> affectations) {
		this.affectations = affectations;
	}

}
