package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "gestion_carburant_db")
public class Categorie implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private int littreParMois;
	private Set<Cadre> cadres = new HashSet<Cadre>(0);

	public Categorie() {
	}

	public Categorie(String libelle, int littreParMois) {
		this.libelle = libelle;
		this.littreParMois = littreParMois;
	}

	public Categorie(String libelle, int littreParMois, Set<Cadre> cadres) {
		this.libelle = libelle;
		this.littreParMois = littreParMois;
		this.cadres = cadres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "libelle", nullable = false, length = 20)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "littre_par_mois", nullable = false)
	public int getLittreParMois() {
		return this.littreParMois;
	}

	public void setLittreParMois(int littreParMois) {
		this.littreParMois = littreParMois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Cadre> getCadres() {
		return this.cadres;
	}

	public void setCadres(Set<Cadre> cadres) {
		this.cadres = cadres;
	}

}
