package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Chauffeur generated by hbm2java
 */
@Entity
@Table(name = "chauffeur", catalog = "gestion_carburant_db")
public class Chauffeur implements java.io.Serializable {

	private String matricule;
	private Employee employee;
	private Set<Mission> missions = new HashSet<Mission>(0);

	public Chauffeur() {
		employee = new Employee();
	}

	public Chauffeur(Employee employee) {
		this.employee = employee;
	}

	public Chauffeur(Employee employee, Set<Mission> missions) {
		this.employee = employee;
		this.missions = missions;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "employee"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "matricule", unique = true, nullable = false, length = 8)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chauffeur")
	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

}
