package com.pfe.gestioncarburant.entities;
// Generated May 23, 2018 7:02:01 PM by Hibernate Tools 5.1.7.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "gestion_carburant_db")
public class Departement implements java.io.Serializable {

	private Integer id;
	private Ville ville;
	private String libelle;
	private Set<Mission> missionsForIdDepartement = new HashSet<Mission>(0);
	private Set<Mission> missionsForIdDepartementDest = new HashSet<Mission>(0);
	private Set<Cadre> cadres = new HashSet<Cadre>(0);

	public Departement() {
	}

	public Departement(Ville ville, String libelle) {
		this.ville = ville;
		this.libelle = libelle;
	}

	public Departement(Ville ville, String libelle, Set<Mission> missionsForIdDepartement,
			Set<Mission> missionsForIdDepartementDest, Set<Cadre> cadres) {
		this.ville = ville;
		this.libelle = libelle;
		this.missionsForIdDepartement = missionsForIdDepartement;
		this.missionsForIdDepartementDest = missionsForIdDepartementDest;
		this.cadres = cadres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_ville", nullable = false)
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@Column(name = "libelle", nullable = false, length = 20)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departementByIdDepartement")
	public Set<Mission> getMissionsForIdDepartement() {
		return this.missionsForIdDepartement;
	}

	public void setMissionsForIdDepartement(Set<Mission> missionsForIdDepartement) {
		this.missionsForIdDepartement = missionsForIdDepartement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departementByIdDepartementDest")
	public Set<Mission> getMissionsForIdDepartementDest() {
		return this.missionsForIdDepartementDest;
	}

	public void setMissionsForIdDepartementDest(Set<Mission> missionsForIdDepartementDest) {
		this.missionsForIdDepartementDest = missionsForIdDepartementDest;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Cadre> getCadres() {
		return this.cadres;
	}

	public void setCadres(Set<Cadre> cadres) {
		this.cadres = cadres;
	}

}
