package com.pfe.gestioncarburant.entities;
// Generated May 16, 2018 6:55:08 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "gestion_carburant_db", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cin"), @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "tel") })
public class Employee implements java.io.Serializable {

	private String matricule;
	private String cin;
	private String nom;
	private String prenom;
	private String email;
	private String adresse;
	private String tel;
	private Chauffeur chauffeur;
	private Cadre cadre;
	private User user;

	public Employee() {
	}

	public Employee(String matricule, String cin, String nom, String prenom, String email, String adresse, String tel) {
		this.matricule = matricule;
		this.cin = cin;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.adresse = adresse;
		this.tel = tel;
	}

	public Employee(String matricule, String cin, String nom, String prenom, String email, String adresse, String tel,
			Chauffeur chauffeur, Cadre cadre, User user) {
		this.matricule = matricule;
		this.cin = cin;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.adresse = adresse;
		this.tel = tel;
		this.chauffeur = chauffeur;
		this.cadre = cadre;
		this.user = user;
	}

	@Id

	@Column(name = "matricule", unique = true, nullable = false, length = 8)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "cin", unique = true, nullable = false, length = 8)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "nom", nullable = false, length = 15)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 15)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "email", unique = true, nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adresse", nullable = false, length = 50)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "tel", unique = true, nullable = false, length = 8)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "employee")
	public Chauffeur getChauffeur() {
		return this.chauffeur;
	}

	public void setChauffeur(Chauffeur chauffeur) {
		this.chauffeur = chauffeur;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "employee")
	public Cadre getCadre() {
		return this.cadre;
	}

	public void setCadre(Cadre cadre) {
		this.cadre = cadre;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "employee")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
